# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossMemberTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nom')),
                ('firstname', models.CharField(max_length=50, verbose_name='Prénom')),
                ('photo', models.ImageField(upload_to='member/photos/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name="Nom de l'équipe")),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ManyToManyField(through='gestion.CrossMemberTeam', to='gestion.Team'),
        ),
        migrations.AddField(
            model_name='crossmemberteam',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Member'),
        ),
        migrations.AddField(
            model_name='crossmemberteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Team'),
        ),
    ]
