# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nom')),
                ('firstname', models.CharField(max_length=50, verbose_name='Prénom')),
                ('photo', models.ImageField(upload_to=gestion.models.Member.get_image_path, verbose_name='Photo')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Job', verbose_name='Fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name="Nom de l'équipe")),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ManyToManyField(to='gestion.Team', verbose_name='Equipe'),
        ),
    ]
