# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cross_member_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='fonction',
            fields=[
                ('gestion_generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.gestion_generic')),
            ],
            bases=('gestion.gestion_generic',),
        ),
        migrations.CreateModel(
            name='groupe',
            fields=[
                ('gestion_generic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.gestion_generic')),
            ],
            bases=('gestion.gestion_generic',),
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fonction')),
            ],
        ),
        migrations.AddField(
            model_name='cross_member_group',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.groupe'),
        ),
        migrations.AddField(
            model_name='cross_member_group',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.member'),
        ),
    ]
