# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20161229_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
    ]
