# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170331_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='right_member',
            name='value',
            field=models.IntegerField(choices=[(0, 'Accès interdit'), (1, 'Accès autorisé')], default=0, verbose_name='Droits'),
        ),
    ]
