# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        ('menu', '0003_right_member_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(0, 'Accès interdit'), (1, 'Accès autorisé')], default=0, verbose_name='Droits')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='Menu')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Team', verbose_name='Equipe')),
            ],
        ),
    ]
