# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_right_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right_member',
            name='value',
        ),
        migrations.RemoveField(
            model_name='right_team',
            name='value',
        ),
    ]
